namespace Cs_Risk_Assessment.Statics
{
	public class Vulnerabilities
	{
		public static readonly List<string> ListOfVulnerabilities = new List<string>
	{
		"Complicated user interface",
		"Default passwords not changed",
		"Disposal of storage media without deleting data",
		"Employees not receiving adequate training",
		"Equipment malfunction",
		"Equipment not replaced",
		"Equipment sensitivity to changes in voltage",
		"Equipment sensitivity to moisture and temperature",
		"Equipment sensitivity to voltage changes",
		"Failure of communication links",
		"Improper cabling security and management",
		"Improper change management",
		"Improper internal audit",
		"Improper validation of processed data",
		"Inadequate backup",
		"Inadequate cabling security",
		"Inadequate change management",
		"Inadequate classification of information",
		"Inadequate control of physical access",
		"Inadequate maintenance",
		"Inadequate network management",
		"Inadequate password management",
		"Inadequate physical protection",
		"Inadequate physical security controls",
		"Inadequate protection of cryptographic keys",
		"Inadequate protection of keys",
		"Inadequate replacement of older equipment",
		"Inadequate security awareness",
		"Inadequate segregation of duties",
		"Inadequate supervision of employees",
		"Inadequate supervision of vendors",
		"Inadequate training",
		"Inadequate training of employees",
		"Incomplete specification for software development",
		"Insufficient data protection",
		"Insufficient processes to prevent data copying",
		"Insufficient processes to prevent malicious files",
		"Insufficient software testing",
		"Lack of access control policy",
		"Lack of control over data flows",
		"Lack of identification systems",
		"Lack of internal audit",
		"Lack of internal audit implementation",
		"Lack of internal documentation",
		"Lack of policy for the use of cryptography",
		"Lack of redundancy",
		"Location vulnerable to flooding",
		"Lack or poor implementation of procedure for removing access rights upon termination of employment",
		"No protection for mobile equipment",
		"Passwords not strong enough",
		"Poor or lack of access control policy",
		"Poor clean desk policy",
		"Poor internal documentation",
		"Poor selection of test data",
		"Premises vulnerable to disruptive events",
		"Premises vulnerable to flooding",
		"Sensitivity to temperature",
		"Single copy of data",
		"Too much power in one person",
		"Uncontrolled copying of data",
		"Uncontrolled download from the Internet",
		"Uncontrolled use of information systems",
		"Uncontrolled use of systems",
		"Undocumented software",
		"Unmotivated employees",
		"Unprotected public networks",
		"Lack of regular user rights reviewed process"
	};
	}
}
